let phonetic_alpha = [
  "Alfa",
  "Bravo",
  "Charlie",
  "Delta",
  "Echo",
  "Foxtrot",
  "Golf",
  "Hotel",
  "India",
  "Juliett",
  "Kilo",
  "Lima",
  "Mike",
  "November",
  "Oscar",
  "Papa",
  "Quebec",
  "Romeo",
  "Sierra",
  "Tango",
  "Uniform",
  "Victor",
  "Whiskey",
  "X-ray",
  "Yankee",
  "Zulu",
];

let animal_names = [
  "Duck breeds",
  "Goose breeds",
  "Pigeon breeds",
  "Turkey breeds",
  "Aardvark",
  "Aardwolf",
  "African buffalo",
  "African elephant",
  "African leopard",
  "Albatross",
  "Alligator",
  "Alpaca",
  "American buffalo (bison)",
  "American robin",
  "Amphibian",
  "list",
  "Anaconda",
  "Angelfish",
  "Anglerfish",
  "Ant",
  "Anteater",
  "Antelope",
  "Antlion",
  "Ape",
  "Aphid",
  "Arabian leopard",
  "Arctic Fox",
  "Arctic Wolf",
  "Armadillo",
  "Arrow crab",
  "Asp",
  "Ass (donkey)",
  "Baboon",
  "Badger",
  "Bald eagle",
  "Bandicoot",
  "Barnacle",
  "Barracuda",
  "Basilisk",
  "Bass",
  "Bat",
  "Beaked whale",
  "Bear",
];

module.exports = uniqueNameGenerator = () => {
  let prefix = animal_names[parseInt(Math.random() * animal_names.length)];
  let suffix = phonetic_alpha[parseInt(Math.random() * phonetic_alpha.length)];

  return `${prefix} ${suffix}`;
};
